### ISSUE TITLE
Hooks have wrong permissions if hooks directory is placed inside state directory

### ISSUE THREAD

**Issue by Flink** [hlandau/acme#106]
I successfully managed to install acmetool with a non root user, everything works fine except if there are hooks in the hooks directory.
If the scripts are executable then acme complains about removing the executable bit but when the file mode is set as documented, then there is this error:

> sudo: /var/lib/dokku/acme/hooks/reload: command not found
20160203185436 [ERROR] acme.hooks: hook script: /var/lib/dokku/acme/hooks/reload: exit status 1

Indeed since there is no executable bit set, sudo can’t run the script. The solution seems to simply enable the executable bit only for the root user and run it with sudo, then it should work.

**Comment by hlandau** [comment]
Ah. So basically, the issue here is that acmetool doesn't expect to have hooks placed inside it's state directory. They're supposed to be separate. One of acmetool's philosophies is to fit neatly into a *nix system, which means following the FHS; so mutable data goes in /var/lib, but executable scripts not intended for direct execution go in /usr/lib[exec].

acmetool should try and obliterate the executable bits you set, but I'm guessing you have the owner set so that this is OK. Which is of course necessary if you want to derive any security from non-root mode, otherwise a malicious acmetool could just write modified sudoable hooks.

Although there's little point in your case since it's so trivial to fix manually, I should note that [it's possible to override the preferred permissions of acmetool as a workaround](https://github.com/hlandau/acme/blob/master/_doc/perm.example). Something like this at `conf/perm` should work:
```
hooks 0755 0755
```

**Comment by hlandau** [comment]
You can also work around this by naming the directory `.hooks`, since filenames beginning with a dot are now ignored. Other than that, since you can use the perms file, I think this is adequately resolved. Executable files shouldn't really be in /var/lib anyway...

**Comment by Flink** [comment]
Just tried the `perm` conf file and it works, thanks!
FYI the hooks are kept in this directory because it’s for a plugin for dokku and so I store all the acme related files under the dokku path (which is in `/var/lib/dokku`). This is where we also store all our plugins so I don’t think it will change for now ;)
