### ISSUE TITLE
Investigate supporting quasselcore

### ISSUE THREAD

**Issue by bong0** [hlandau/acme#107]
It would be nice if the tool could put a file in the `/live` folder which is just a concatenated version of privkey, cert and maybe also the rest of the chain.

Some applications like quasselcore don't accept separated files.

**Comment by hlandau** [comment]
The HAProxy hook does this, but acmetool only offers to install it if it detects HAProxy or Hitch.

I'll have to investigate quasselcore. In the meantime, you can grab the hook manually here: https://github.com/hlandau/acme/blob/master/cmd/acmetool/quickstart.go#L143-L181

Save it as /usr/lib[exec]/acme/hooks/haproxy, make it executable.
Remove the symlinks so that when acmetool is run, it runs the hooks again: `rm /var/lib/acme/live/*`
Run acmetool: `acmetool`
You now have combined certificate and private key files at `/var/lib/acme/live/HOSTNAME/haproxy`.

**Comment by bong0** [comment]
okay cool, thanks! I thought about an alternative/more general solution for that case which does not depend on certain application names and behaviour hardcoded but you know better in which direction you want to develop :) I'm happy to provide suggestions though.

**Comment by hlandau** [comment]
I should probably generalise it, yes. Maybe I'll rename the HAProxy prompt in the installation wizard to 'Install hook for applications requiring combined certificate+key files?`. Probably I'd only show it if HAProxy or Hitch or Quasselcore is detected, or --expert is passed.

**Comment by bong0** [comment]
Yes I find your proposed prompt well suited for this. I'm not very convinced of the restriction to to --expert since people may not try doing this when just having discovered the software. Especially without note in the docs.

My proposal: show that prompt but with a default-no answer since it's not a common case and people should know if they have such an application running (since they needed to cat cert+keys in the past). 

There is an issue with permission set to the /live/HOST/haproxy file: it's owned by root and 0600 per default which is not sufficient to quasselcore since it has its own user. 

I opened an issue since it got too lengthy: https://github.com/hlandau/acme/issues/108

The haproxy script needs to be modified for this: (umask + chown)
```
# Create coalesced files and a haproxy repository.
mkdir -p "$ACME_STATE_DIR/haproxy"
umask 7037 # rescrict to 0740

while read name; do
  certdir="$ACME_STATE_DIR/live/$name"
  if [ -z "$name" -o ! -e "$certdir" ]; then
    continue
  fi
  if [ -n "$HAPROXY_DH_PATH" -a -e "$HAPROXY_DH_PATH" ]; then
    cat "$certdir/privkey" "$certdir/fullchain" "$HAPROXY_DH_PATH" > "$certdir/haproxy"
  else
    cat "$certdir/privkey" "$certdir/fullchain" > "$certdir/haproxy"
  fi
  chown "$USER":ssl-cert "$certdir/haproxy"
  [ -h "$ACME_STATE_DIR/haproxy/$name" ] || ln -s "../live/$name/haproxy" "$ACME_STATE_DIR/haproxy/$name"
done
```
Calling `acmetool` then results in 
```
root@vm:/var/lib/acme# acmetool
20160204131222 [WARN] fdb: broken symlink, removing: /var/lib/acme/haproxy/example.com -> ../live/example.com/haproxy
```
though, which seems not to be important for me currently but I want you to know.

**Comment by hlandau** [comment]
Come to think of it, the `haproxy` script actually doesn't do anything unless haproxy or hitch is detected. So installing the `haproxy` script unconditionally would be inconsequential, unless someone doesn't want to generate those files even though haproxy is installed...

So what I might do is the opposite: always install the hook *unless* `--expert` is specified, in which case ask.

**Comment by bong0** [comment]
A quick note on this: you should also detect vsftpd which also accepts **yet another** combination: **domaincert+certcain** in one file! :/
Maybe two files in the future?:
  - keybundle (privkey+cert+chain)
  - certbundle (cert+chain)

To your note that the haproxy hook only runs when it detects haproxy: I patched that line out for me, sure ;)

One note on your commit 99d5f4a171c4fc7cad5ce9a1f943b3cea831390c: You could also softlink the haproxy file to a new "keybundle" file

**Comment by hlandau** [comment]
You'll note that the new haproxy hook lets you specify the services to detect or just force it.
It looks like vsftpd can accept the same format? Takes privkey+fullchain in one file, like HAProxy. Or does it need to be in the order fullchain+privkey?

The documentation indicates that you can put the private key in another file and specify it with rsa_private_key_file, so it's not essential to do this via combined files. In that regard, I think I'd rather leave vsftpd out of the default list of daemons requiring combined files, since it's possible to configure it to work correctly without.

**Comment by bong0** [comment]
@hlandau right, you refer to the helppage "rsa_private_key_file .... This option specifies the location of the RSA private key to use for SSL encrypted connections. **If this option is not set, the private key is expected to be in the same file as the certificate.**"

Good news: I just checked it: vsftpd supports having the combined file with privkey first and then fullchain! :)
