### ISSUE TITLE
Consider having reconcile --batch mode return status codes

### ISSUE THREAD

**Issue by FrancisRussell** [hlandau/acme#129]
For having an external script perform actions depending on the behaviour of acmetool, it would be nice if "acme reconcile --batch" could return a status code (in a manner similar to simp_le) that indicated if acmetool had changed any certificates (possibly only enabled with another command line option to avoid breaking scripts with "set -e").

I know the notification hooks functionality exists, but I want to copy the generated certs to a new location before services are restarted and it's unclear if hook execution is ordered and I'd need to make sure my hook executed before the reload hook (installed by the Ubuntu package). Also, I'd just like to stick all control logic related to certificate updates in a single location.

**Comment by hlandau** [comment]
Hook execution is guaranteed to be ordered in lexicographic ascending order by filename of file in the hooks directory. Naming a hook '00foo' should do what you need.

**Comment by hlandau** [comment]
Having nonzero success exit codes seems like a really big deviation from standard UNIX practice, and it feels like bloat to me. It's just a bit too marginal, since you can do this so effectively with the hooks.

You mention you want to copy the generated certificates before services are restarted, but I don't see how an exit code helps with that; by the time the exit code is returned, all hooks have been executed. On the other hand, if you name a hook `00foo` then acmetool won't do anything, such as executing the reload hook, until it returns.

Of course the use of the reload hook is always optional; if you don't want to use it replace it with an empty, non-executable file, or a file containing

```
#!/bin/sh
exit 42 # operation not supported
```

and of course you can always customize the default scripts so long as you remove the `#!acmetool-managed!#` line to prevent overwriting it with updated versions.

**Comment by FrancisRussell** [comment]
I'm not sure it's that much of a deviation from Unix practice. The closest parallel is probably make which does have some basic support for distinguishing between different results.

>  GNU  make  exits  with  a  status  of zero if all makefiles were successfully parsed and no targets that were built failed.  A status of one will be returned if the -q flag was used and make determines that a target needs to be rebuilt.  A status of two will be returned if any errors were encountered.

If calling acmetool from an external script, one would probably disable the hooks functionality (though there doesn't seem to be an easy way to do this except supplying an empty hooks dir) then do anything needed afterwards like copying certs then restarting services itself.

I guess I have an aversion to the notification hooks functionality. It feels like doing things like reloading the webserver etc. overstep the bounds of a tool meant primarily to retrieve new certs. 

Feel free to close if you think the exit code stuff would add bloat. However, I do feel that an option that disables hook execution might be useful for those who want to script acmetool without the possibility of side-effects triggered by whatever notification hooks have been installed.

**Comment by hlandau** [comment]
There's no obligation to use the notification hooks functionality to reload webservers. The default scripts are installed by quickstart, and after that can be modified or removed arbitrarily. Alternatively you can actually run without running quickstart. It's completely up to you what you use, or don't use it for. An easy way to disable hooks would be `--hooks=/var/empty`.

I'm going to close this since this feels very marginal to me, but maybe I'll revisit it if more people ask for it...
