### ISSUE TITLE
RFE: Link libcap statically into the binaries if possible

### ISSUE THREAD

**Issue by kkofler** [hlandau/acme#17]
I am using acmetool on CentOS 5 since it seems very hard to get the official client to run on such an old operating system. Unfortunately, `libcap.so.2` is not available there. The binary runs, apparently without issues, if I `sed -i -e s/libcap\.so\.2/libcap.so.1/g acmetool` (and also workaround the `whiptail` issue I'm filing next), but this is a horrible hack that I do not want to have to do.

Is it possible to link `libcap` statically? (That said, you need to be careful to not introduce a requirement for a too new `glibc` that way, which would only make things worse. At this time, `acmetool` works fine with the `glibc` 2.5 in CentOS 5. The highest requested symbol version I found was actually `GLIBC_2.3.4`.)

**Comment by hlandau** [comment]
If you're willing to build yourself, you could try this. I can't really support it since my distro doesn't even offer statically linked libcap.

Edit `gopkg.in/hlandau/service.v2/daemon/caps/caps-linuxc.go`. Change `#cgo LDFLAGS: -lcap` to `#cgo LDFLAGS -Wl,-Bstatic -lcap -Wl,-Bdynamic`.

Alternatively build with cgo disabled by setting env CGO_ENABLED=0 and building. This is inconsequential if you aren't using the redirector. If you are, [some restrictions apply.](https://github.com/hlandau/service/tree/v2.0.10#reduced-functionality-mode)

**Comment by kkofler** [comment]
While I think you could probably obtain a `libcap.a` from somewhere to link your binaries against, I suppose the simplest (non-hack) fix is for me (any anybody else stuck on CentOS 5) to just install the `libcap2` package from:
http://www.pramberger.at/peter/services/repository/

I did the following:
```sh
su -
cd /etc/yum.repos.d/
wget 'http://devel.pramberger.at/getrepo?release=5' -O pp.repo
sed -i -e 's/enabled=1/includepkgs=libcap2\nenabled=1/g' pp.repo
yum install libcap2
```
and there we go, I have a `libcap.so.2` now.
