### ISSUE TITLE
"desired" files interfere while adding new domains

### ISSUE THREAD

**Issue by fauno** [hlandau/acme#172]
As I'm adding new subdomains to a single SAN certificate I've noticed sometimes the new subdomain doesn't appear on the certificate, or the want command succeeds but no new cert is issued, or the batch reconcile "restarts" the certificate to a previous state where the new subdomain is also missing.

I've found there's a lot of files in the "desired" directory for the same domain so it seems to me the want command is giving priority to one of them instead of using the latest list of desired domains or the ones I'm giving it myself like this:

```bash
acmetool want domain subdomain1 subdomain2
# a few days later
acmetool want domain subdomain1 subdomain2 subdomain3
```

The problem goes away if I remove any files on the desired directory and run the want command.

**Comment by hlandau** [comment]
This is correct behaviour. Running 'want' generates a targetfile. A targetfile expresses requirements which must be satisfied. A certificate satisfies a targetfile if it contains a superset of the names expressed therein. Thus a certificate for subdomain1, subdomain2 and subdomain3 satisfies a target for subdomain1, subdomain2.

**Comment by fauno** [comment]
Hugo Landau <notifications@github.com> writes:

> This is correct behaviour. Running 'want' generates a targetfile. A
> targetfile expresses requirements which must be satisfied. A
> certificate satisfies a targetfile if it contains a superset of the
> names expressed therein. Thus a certificate for subdomain1, subdomain2
> and subdomain3 satisfies a target for subdomain1, subdomain2.

i see, but the way i experienced it, subdomain3 is ignored until i
remove any previous targetfile...

-- 
:D

**Comment by hlandau** [comment]
That shouldn't be the case.

If you can construct a test case for this using the staging server and documenting the exact sequence of acmetool commands leading to such behaviour, I can determine if this is a bug.

**Comment by fauno** [comment]
sorry, didn't have time to do it.  i'll ping here when i can test it :)

-- 
http://utopia.partidopirata.com.ar/

**Comment by md2k** [comment]
Not looks like it is a bug, since it generates all certificates properly (did several tests).
Acme checks to which desired target file certificate satisfied and pickup best one, and continue its work, if i add new domain to want command with previous, already generated certificates, Acme checks that new request not satisfied to current desired file and generates new, which will be used later.
But i think it will be nice to have automated cleanup of desired files which is not required anymore, simply keep directory clean, from other side you always can remove dups using file time sort and keep most actual file.
