### ISSUE TITLE
Question about Directory Schema 

### ISSUE THREAD

**Issue by md2k** [hlandau/acme#192]
Current accounts folder looks like:
```
accounts/
        acme-v01.api.letsencrypt.org%2fdirectory/
                accountID
                .....
```
`%2f` it is URL encoded ASCII code `/`
and in official Letsencrypt client folder structure looks like 
```
accounts/
        acme-v01.api.letsencrypt.org/
                directory/
                        accountID
                .....
```
Maybe it is better to fix folder structure, since using symbol `%2f` in file name may cause problems  under other OS and `acme-v01.api.letsencrypt.org%2fdirectory/` is `acme-v01.api.letsencrypt.org/directory/` so it will be more logically have folder structure as `api.server/directory/accountIDn`

**Comment by asquelt** [comment]
that would make backward incompatible change, so it should be probably limited to the specific "other os" .

**Comment by md2k** [comment]
I think such incompatibility pretty easy to solve with few lines of bash script which will create correct folder and move required data into it.
For sure it will require some manual interactions, but i think it is better to do it at some point.

**Comment by asquelt** [comment]
i run acmetool in container with volume overmounted on /var/lib/acme.
docker-compose just reimage it every time there is new release happening on github.
i don't think there is any manual interaction happening in there. in fact, there is even no bash in there.

**Comment by hlandau** [comment]
This was a deliberate design decision. I decided that the directory URL for a given ACME endpoint shouldn't cause arbitrary directory trees. It's an opaque identifier, and has no structure in the eyes of the ACME client. Plus, URLs aren't necessarily valid filenames. So if I have an ACME directory URL `https://foo.com/dir:ectory`, and a filesystem which prohibits `:` (or even assigns special meaning to it - think NTFS alternate streams, although that's rather academic since acmetool is designed for POSIXy systems alone), what then?

The only issue with this scheme is whether `%` is a good choice on all platforms. It works on *nix and Windows (though that's moot), so I don't see the issue with it. Note that this encoding extends to all unusual characters which may not be usable on a filesystem, not just `/`.
