### ISSUE TITLE
HAProxy support

### ISSUE THREAD

**Issue by asquelt** [hlandau/acme#2]
haproxy requires pem file composed of key/cert/intermediates/dhparams which is not covered by acme-sss.
the hook below assembles this pem and instructs haproxy to reload.
i'm not sending PR as your code has 'reload' hook baked in, please decide whether any additional hooks should be placed somewhere in distribution. feel free to use it:
https://gist.github.com/asquelt/77435c9061c84d7aebff

**Comment by hlandau** [comment]
Hmm, this is troublesome. It's unfortunate that HAProxy requires these be coalesced into the same file.

In order to support this, the sanest way would I suppose to be to add a new file in every cert directory, call it `fullchain+privkey` or something. This duplicates the private key, and undermines the idea that ./accounts and ./keys are private and everything else public. It shouldn't go in the key directory, because the same key could legitimately be used for multiple certificates (e.g. when renewing; currently acmetool always makes a new certificate but it's not hard to imagine an option not to could be useful for people doing pinning).

The need to include the DH parameters complicates things further, as this is simply out of scope for ACME.

HAProxy support is important, but I'm not immediately sure what to do about this. So for now, I've added a notification hook which the quickstart wizard only offers to install if you have HAProxy installed. The coalesced file is created at `$ACME_STATE_DIR/live/HOSTNAME/haproxy`. The standard hook has also been updated to list haproxy in its services list.

**Comment by asquelt** [comment]
to add a pinch of salt - haproxy expects to have clean directory with its certificates (to map cert altnames with SNIs) and it assumes other naming conventions for stapling and certificate transparency (https://cbonte.github.io/haproxy-dconv/configuration-1.6.html#5.1-crt).

**Comment by hlandau** [comment]
So it looks like you don't need to put DH params in the certificate file, you can use [ssl-dh-param-file](https://cbonte.github.io/haproxy-dconv/configuration-1.6.html#3.1-ssl-dh-param-file) instead. This is probably saner.

What if I update the notify hook to create the following structure:
```
/var/lib/acme
  certs
    ...
      haproxy  ;; (privkey, cert, intermediates)
  haproxy
    example.com -> ../live/example.com/haproxy
    example.com.oscp   ;; empty file
```

SCT support would be an interesting TODO.

**Comment by asquelt** [comment]
ssl-dh-param-file is exclusive for 1.6, while 1.5 is still widespread and supported.

**Comment by hlandau** [comment]
`/var/lib/acme/haproxy` is now created by the HAProxy hook script, which contains symlinks to the `haproxy` files.

On further reflection, I think doing this via hook script is actually quite nice, and demonstrates the power of the hook script system. So I think this more than suffices to resolve this issue.
