### ISSUE TITLE
i don't use port 80/443

### ISSUE THREAD

**Issue by tiggerfan** [hlandau/acme#285]
Hi,

I don't run my server on port 80 nor 443.  I tried doing the setup using the Redirector mode but it fails because my SSL is not on port 443.  I also don't want port 80 redirected to my SSL port as i do not advertise that port and don't want scanners finding it by being redirected to it from 80. So how does one obtain/renew a cert when you don't use 443 nor 80.

**Comment by hlandau** [comment]
The only way to obtain a certificate from Let's Encrypt is via authentication via port 80, 443, or via the dns authentication method. There is no other way; this is a deliberate policy of Let's Encrypt, not a limitation of acmetool. See https://letsencrypt.org/ or the ACME specification for details.

Since you're not listening on port 80 or 443, acmetool should be able to obtain certificates by listening on these ports while it is being executed. This listening is only momentary; it will be for a few seconds every two months, approximately, since the listening is only while certificates are being acquired.

**Comment by tiggerfan** [comment]
I'm find with a few seconds a month and i did try the redirector but it fails and the debug is not helpful determining why.  I did start the redirector manually first.  where are the log files for the redirector?

**Comment by tiggerfan** [comment]
nevermind i found it
