### ISSUE TITLE
multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by Thermi** [hlandau/acme#293]
acmetool doesn't build on Arch with the following error message:
```
# github.com/hlandau/acme/storage
../fakegopath/src/github.com/hlandau/acme/storage/types.go:197:17: multiple-value uuid.NewV4() in single-value context
```

**Comment by siebenmann** [comment]
This issue is due to an upstream API change in the [github.com/satori/go.uuid](https://github.com/satori/go.uuid) package, specifically the change for https://github.com/satori/go.uuid/issues/18. A number of people have raised issues against go.uuid about this being a breaking API change, so there's a chance that it will be reverted at some point.

(It's possible to work around this to build Acme with a small code change, or in go.uuid by checking out a version before this breaking API change.)

**Comment by Thermi** [comment]
Thank you for the response. Would you please provide a patch for that?

**Comment by legion-zver** [comment]
// New version
u, err := uuid.NewV4()
obj.uuid = u.String() 

// I would like to be able to
obj.uuid = uuid.MustNewV4().String()

// If error to send panic for MustNewV4

**Comment by xiaodi2015** [comment]
id,_ := uuid.NewV4()

**Comment by AlessandroRuggiero** [comment]
when i run go build i get:

```
# github.com/googollee/go-socket.io
../../googollee/go-socket.io/redis_broadcast.go:126:21: multiple-value uuid.NewV4() in single-value context
../../googollee/go-socket.io/redis_broadcast.go:358:26: multiple-value uuid.NewV4() in single-value context
../../googollee/go-socket.io/redis_broadcast.go:459:26: multiple-value uuid.NewV4() in single-value context
../../googollee/go-socket.io/redis_broadcast.go:497:26: multiple-value uuid.NewV4() in single-value context
```

even if i use glide.

it is an error with the redis broadcaster, is there a workaround?
I don't think I even need the redis broadcaster
