### ISSUE TITLE
ACMEv2 implementation progress

### ISSUE THREAD

**Issue by bago** [hlandau/acme#294]
Hi Hugo,
thanks for acmetool!

Do you have any plan/roadmap to support ACME-v2?

https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605
https://letsencrypt.org/2017/06/14/acme-v2-api.html

**Comment by simonszu** [comment]
Acme v2 went live today. Still no answer on this issue since two months. Guess I'll have to switch to certbot.

**Comment by Jean-Daniel** [comment]
There is many alternatives that supports it. No need to fall back to the certbot piece of junk (search for acme.sh on GitHub for instance)

**Comment by hlandau** [comment]
Yes, support will be published soon.

**Comment by hlandau** [comment]
ACMEv2 support is being developed in the `acmev2` branch. Consider that:
- It is *very alpha*.
- Wildcard certificates are supported. e.g. `acmetool want '*.example.com'`. Since Let's Encrypt requires the use of the DNS challenge for wildcard certificates, having a DNS challenge hook script setup is mandatory for this.
- ACMEv1 support is removed, since all available endpoints (Let's Encrypt) now support ACMEv2.
- The old Let's Encrypt production directory URL will be automatically converted to the correct ACMEv2 URL.
- That said, full support for seamless in-place upgrades from acmetool v0.0.x **is not yet complete.** Use a fresh `/var/lib/acme`, or at the very least make backups of your existing one. Otherwise, expect breakage.
- The `acmeapi` package, which was originally in the same repository, has been factored out to a separate repository, https://github.com/hlandau/acmeapi. This package targets ACMEv2 only.
- https://github.com/hlandau/acme will be renamed to `https://github.com/hlandau/acmetool` once v0.2.1 is released. The old URL will redirect. Also, `go install https://github.com/hlandau/acmetool` will be the preferred installation method, and `go install https://github.com/hlandau/acme[tool]/cmd/acmetool` will be deprecated, but still work.
- Since it's an alpha, don't use it for critical purposes and don't expect it to work well.
- Bug reports for this alpha are welcome. Please create an issue with title beginning `acmev2: `.
- Expect further significant changes.

**Comment by hlandau** [comment]
Closing this since the core implementation is done. Further work will follow before release.
