### ISSUE TITLE
Running make messes up the repository

### ISSUE THREAD

**Issue by w00kie** [hlandau/acme#46]
Running the `make` command basically rewrites the whole directory, even removing the `.git` folder. So I clone the repo, run `make & make install` and then if some update is released, I need to trash that folder and re-clone the repo instead of pulling the new code.

**Comment by hlandau** [comment]
I should probably add an update command, yes. You can just run:
```
GOPATH="$(pwd)" go get -u github.com/hlandau/acme/...
```
in the directory containing the Makefile (or `git pull` from src/github.com/hlandau/acme, but that won't update dependencies.)

This behaviour is intentional and due to how Go code management works. By cloning the repo, you're cloning the code, but the code needs to be at $GOPATH/src/github.com/hlandau/acme, so it moves the code into that location, using the current directory as GOPATH if no GOPATH is set.

If you prefer, you can setup a GOPATH and just use `go get`. This is the preferred option for users familiar with Go.
